### ISSUE TITLE
Exception crash in latest version

### ISSUE THREAD

**Issue by skabning** [Hyrules/WinHue#247]
Happens every launch. Hub and all lights are updated.

[WinHue3 2019-06-30.txt](https://github.com/Hyrules/WinHue/files/3343222/WinHue3.2019-06-30.txt)

I hope this can be resolved! Thank you very much.
As an aside, I just deleted 4,5GB of old log files. Some of them were 188MB large!

**Comment by Hyrules** [comment]
WinHue crashes because it expect a property of certain schedule aka localtime which are not present in some of your schedules. time is depected and should not be used anymore. I will try to add a check for this as for the logs I will try to limit the size and roll files.

**Comment by Hyrules** [comment]
This should be fixed in this version : 
[WinHue 3.0.4721.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3350294/WinHue.3.0.4721.0.Setup.zip)

**Comment by skabning** [comment]
Works perfectly, thank you very much!

**Comment by skabning** [comment]
Hello again! It seems the app now crashes after returning from sleep.
[WinHue3.txt](https://github.com/Hyrules/WinHue/files/3354731/WinHue3.txt)

Additionally, I had to manually add .txt to the log file name. I'm not sure if this is intended behavior :)

**Comment by Hyrules** [comment]
Here this should fix this error let met know what happens :

[WinHue 3.0.4723.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3355123/WinHue.3.0.4723.0.Setup.zip)

**Comment by skabning** [comment]
Everything seems to be working! Thank you for your quick response.

**Comment by DietzMix** [comment]
All of a sudden I get crashes from WinHue, too. I installed the latest build you linked to above (4723.0), to no avail:

"Sorry but an unexpected exception occured. Please report the exception on the support website so the developper can fix the issues. Please include the most recent log located in the logs folder."

[WinHue3 2019-07-05.txt](https://github.com/Hyrules/WinHue/files/3363858/WinHue3.2019-07-05.txt)

Win 7 Prof. 64 bit

**Comment by Hyrules** [comment]
2019-07-05 21:38:51,825 [1] INFO  WinHue3.App [Application_Startup:48] ==> WinHue 3.0.4718.0 started

From your log you are not running 4723 but 4718. install the version in this topic and let me know if you still have the error and a fresh log with it in case not.

**Comment by DietzMix** [comment]
Hmmm ... the GUI tells me something different, sorry to say so: -> Screenshot:
![WinHue3_Error](https://user-images.githubusercontent.com/52582593/60746476-35930000-9f7f-11e9-9e60-cceaa065e029.png)

**Comment by DietzMix** [comment]
... it seems as no log-files get written at all since the issue started. 
![WinHue3_LogError](https://user-images.githubusercontent.com/52582593/60746662-56a82080-9f80-11e9-8114-cd672932c888.png)

**Comment by Hyrules** [comment]
In the WinHue Folder are you settings files ok ?

**Comment by Hyrules** [comment]
You can try this version but I doubt it will fix anything . [WinHue 3.0.4724.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3364113/WinHue.3.0.4724.0.Setup.zip)

**Comment by DietzMix** [comment]
> 
> 
> In the WinHue Folder are you settings files ok ?

Sorry - I don't understand?

**Comment by DietzMix** [comment]
> 
> 
> You can try this version but I doubt it will fix anything . [WinHue 3.0.4724.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3364113/WinHue.3.0.4724.0.Setup.zip)

No, like you said, this version didn't fix the error.

Is there a version archive somewhere? It seems as the error appeared with the most recent update 4718.

**Comment by Hyrules** [comment]
What I was meaning was to check your configuration files in the WinHue folder. One folder above the log folder. You should have 3 files with extensions set :

WinHueBridges.set - Bridge settings
WinHueHotkeys.set - Hotkeys settings
WinHueSettings.set - WinHue settings

Can you read those files with a text editor like notepad or notepad++ ? I want to see if they are corrupted. Do you see any kind of corruption in the files ? like weird characters other than normal 

Yes there are some archived version in the release page of this [github page](https://github.com/Hyrules/WinHue/releases) but if you install one you wont be able to help me fix this issue. If you have it chances are other will and you wont be able to upgrade to latest version because you will always have this issue in the next releases.

**Comment by Hyrules** [comment]
I just got an Idea let me get you another release this will clarify the error message and maybe point me in the right direction for a fix.

**Comment by Hyrules** [comment]
Here this version will give a better error message :

[WinHue 3.0.4730.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3364716/WinHue.3.0.4730.0.Setup.zip)

**Comment by DietzMix** [comment]
Thanks for your efforts! This is the error message I get from build 4730:



---------------------------
Sorry but an unexpected exception occured. Please report the exception on the support website so the developper can fix the issues. Please include the most recent log located in the logs folder.



Error message : Object reference not set to an instance of an object.

Source : WinHue3

Date : System.Collections.ListDictionaryInternal

Stack :    at WinHue3.MainForm.MainFormViewModel.LoadBridges() in D:\Documents\Visual Studio 2015\Projects\WinHue\WinHue3\MainForm\MainFormViewModel_Bridge.cs:line 359

   at WinHue3.MainForm.MainFormViewModel.Initialize() in D:\Documents\Visual Studio 2015\Projects\WinHue\WinHue3\MainForm\MainFormViewModel.cs:line 97

   at WinHue3.MainForm.MainFormViewModel.<get_InitializeCommand>b__109_0(Object param) in D:\Documents\Visual Studio 2015\Projects\WinHue\WinHue3\MainForm\MainFormViewModel_Commands.cs:line 246

   at WinHue3.Utils.RelayCommand.Execute(Object parameter) in D:\Documents\Visual Studio 2015\Projects\WinHue\WinHue3\Utils\RelayCommand.cs:line 44

   at WinHue3.Functions.Behaviors.WindowContentRenderedBehavior.OnWindowContentRendered(Object sender, EventArgs e) in D:\Documents\Visual Studio 2015\Projects\WinHue\WinHue3\Functions\Behaviors\WindowContentRenderedBehavior.cs:line 42

   at System.Windows.Window.OnContentRendered(EventArgs e)

   at System.Windows.Window.<PostContentRendered>b__198_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)

   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)

   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

   at System.Windows.Application.RunDispatcher(Object ignore)

   at System.Windows.Application.RunInternal(Window window)

   at System.Windows.Application.Run(Window window)

   at System.Windows.Application.Run()

   at WinHue3.App.Main()

**Comment by DietzMix** [comment]
Re: Setting files:

> WinHueBridges.set - Bridge settings  .... is empty
> WinHueHotkeys.set - Hotkeys settings   .... contains readable text
> WinHueSettings.set - WinHue settings  .... contains readable text

Sidenote: Still no new log-file entrances.

**Comment by Hyrules** [comment]
Empty is not ok. It should not be empty. Try deleting the file.

**Comment by Hyrules** [comment]
Yeah ok I got the crash ! It seems that an empty file will give an exception. I will fix this stay close I will have a new version for you to test and THe error message box is huge i will try to make a custom one which one can copy and paste.

**Comment by Hyrules** [comment]
Here you go this should fix the issue you are having. I have not added the error window yet but I will next. Meanwhile you should be good to go. 

[WinHue 3.0.4732.0 Setup.zip](https://github.com/Hyrules/WinHue/files/3364933/WinHue.3.0.4732.0.Setup.zip)

**Comment by DietzMix** [comment]
Thanks for the update. First I got pretty much the same error message as the one I posted before, but following your comment I deleted "WinHueBridges.set" - this did the trick. I had to pair the app with the bridge again, but now all is well.

Thanks a bunch for your help! Highly appreciated.

**Comment by Hyrules** [comment]
Thanks for sticking with me on this. This should not occur in the next release has I have added a check to prevent this type of crash when the file is empty.

**Comment by Hyrules** [comment]
fixed in the latest version.
