### ISSUE TITLE
Program crashes multiple times per day

### ISSUE THREAD

**Issue by MitchConner912** [Hyrules/WinHue#266]
I've tried uninstalling and completely removing then reinstalling. Tried re-pairing. Factory reset bridge. Nothing works. Crashes are seemingly random but occur multiple times per day. Always same error as shown below "Object reference not set to an instance of an object." This has been going on for over two months. Tried newer versions as they came out with no luck. Current version is latest. Any suggestions?

```
Error message : Object reference not set to an instance of an object.
Source : WinHue3
Data : System.Collections.ListDictionaryInternal
Stack :    at WinHue3.Philips_Hue.BridgeObject.Bridge.<>c.<GetAllObjectsAsync>b__73_0(IHueObject x) in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\Philips Hue\BridgeObject\Bridge_ObjectGetter.cs:line 117
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at WinHue3.Philips_Hue.BridgeObject.Bridge.<GetAllObjectsAsync>d__73.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\Philips Hue\BridgeObject\Bridge_ObjectGetter.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WinHue3.MainForm.MainFormViewModel.<_refreshTimer_Tick>d__58.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\MainForm\MainFormViewModel_Bridge.cs:line 450
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()
```

**Comment by Hyrules** [comment]
I would need the rest of the log. This alone does not help. Plus there more info I need like the version of your bridge api and most likely a dump of your bridge items so I can try to find what is causing the crash.

**Comment by MitchConner912** [comment]
If I zip my appdata folder, will that provide you with everything you need? Are bridge items included in the appdata folder or will I need to obtain that some other way?

**Comment by Hyrules** [comment]
The log should be located in the appdata folder under WinHue\log the other things you will need to get some other way. For the dump of the bridge there is an option in the main menu called export config. I will need a full datastore. The Api version is located under Modify Bridge settings (gear icon in the main window) under Api Version.

**Comment by MitchConner912** [comment]
Full data dump, versions, and appdata folder are included:

https://drive.google.com/open?id=11MjGY_xnGgD6x5abBJskSpILNRAdV65B

**Comment by Hyrules** [comment]
ok first this you will need to do is update your bridge. Your api version says it's at 1.16 which is way too old. WinHue does not support this version thus you are having some crashes. You can try to use WinHue to update the bridge but it might not work right away. In the same windows ( gear icon ) as the api version there is a tab Software Update Information. There you should be able to update your bridge if not your going have to use the official android or apple app.

**Comment by MitchConner912** [comment]
I have the V1 bridge and the V1 app on android states there are no updates available for my bridge. When I try to update on WinHue, it crashes just before it can finish. I have tried updating in the past before I had this specific crash issue but it would never update via app or WinHue. My bridge wouldn't be defective, would it?

**Comment by Hyrules** [comment]
This will be a problem. The V1 is coming to EOL (End of life) meaning that Philips won't support them soon. The only thing I can recommend at this point is to get a V2. Those are cheap when bought alone without any bulb. From what I see on philips page there are no more update after the one you have for the V1 bridge. So basically there is nothing I can do.

**Comment by MitchConner912** [comment]
Alright. Guess I'll just have to get the new bridge. Thanks for taking the time to help.

**Comment by Hyrules** [comment]
No problem there. If you even have any problem with the new ones and WinHue. I will be happy to help.
