### ISSUE TITLE
Crash when editing a 'Recourse Link'

### ISSUE THREAD

**Issue by Luuk34** [Hyrules/WinHue#279]
Before submitting a request please make sure you are running the latest version of WinHue 
available in the release section of this site. Support will not be done on older version.

### Your setup 

WinHue version : (eg. 3.0.4743.0)
Bridge api version : (1.36)
Light model : (if you have a problem with a particular light)

### Expected behavior and actual behavior
not crash, but warn, or show what is 'missing'....
...

### Actual behavior
crash when editing 'Recourse Link', by richt clicking it and choose 'edit'
...

### Steps to reproduce the problem

1) Right-click 'resource link', and choos edit.
2) --> Crash

In the case of a crash, please make sure to add a logfile containg the crash located in the %APPDATA%\WinHue3
to the issue you are opening.
2020-02-26 10:35:44,329 [1] DEBUG WinHue3.Philips_Hue.Communication.Serializer [DeserializeToObject:110] ==> {"name":"Group 0","lights":["1","2","3","4"],"sensors":["1","2","3","4","6","9","10","12","13","14","15","17","18","19"],"type":"LightGroup","state":{"all_on":false,"any_on":false},"presence":{"state":{"presence":true,"presence_all":true,"lastupdated":"2020-02-25T18:58:48"}},"recycle":false,"action":{"on":false,"bri":254,"ct":366,"alert":"select","colormode":"ct"}}
2020-02-26 10:35:46,698 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:97] ==> Unexpected Exception : 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at WinHue3.Functions.ResourceLinks.ResourceLinkCreatorViewModel.set_Resourcelink(Resourcelink value) in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\Functions\ResourceLinks\ResourceLinkCreatorViewModel.cs:line 60
   at WinHue3.Functions.ResourceLinks.Form_ResourceLinksCreator.<Initialize>d__4.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\Functions\ResourceLinks\Form_ResourceLinksCreator.xaml.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinHue3.MainForm.MainFormViewModel.<EditObject>d__315.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\MainForm\MainFormViewModel_Methods.cs:line 897
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinHue3.Utils.AsyncRelayCommand.<Execute>d__9.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\WinHue Dev\WinHue3\Utils\AsyncRelayCommand.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WinHue3.App.Main()
2020-02-26 10:35:46,704 [1] FATAL WinHue3.App [CurrentDomain_UnhandledException:98] ==> {"ClassName":"System.InvalidOperationException","Message":"Sequence contains no matching element","Data":{"System.Object":null},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at WinHue3.Functions.ResourceLinks.ResourceLinkCreatorViewModel.set_Resourcelink(Resourcelink value) in C:\\Program Files (x86)\\Jenkins\\workspace\\WinHue Dev\\WinHue3\\Functions\\ResourceLinks\\ResourceLinkCreatorViewModel.cs:line 60\r\n   at WinHue3.Functions.ResourceLinks.Form_ResourceLinksCreator.<Initialize>d__4.MoveNext() in C:\\Program Files (x86)\\Jenkins\\workspace\\WinHue Dev\\WinHue3\\Functions\\ResourceLinks\\Form_ResourceLinksCreator.xaml.cs:line 86\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at WinHue3.MainForm.MainFormViewModel.<EditObject>d__315.MoveNext() in C:\\Program Files (x86)\\Jenkins\\workspace\\WinHue Dev\\WinHue3\\MainForm\\MainFormViewModel_Methods.cs:line 897\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at WinHue3.Utils.AsyncRelayCommand.<Execute>d__9.MoveNext() in C:\\Program Files (x86)\\Jenkins\\workspace\\WinHue Dev\\WinHue3\\Utils\\AsyncRelayCommand.cs:line 53\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   at System.Windows.Threading.DispatcherOperation.InvokeImpl()\r\n   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Windows.Threading.DispatcherOperation.Invoke()\r\n   at System.Windows.Threading.Dispatcher.ProcessQueue()\r\n   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)\r\n   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)\r\n   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)\r\n   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)\r\n   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)\r\n   at System.Windows.Application.RunDispatcher(Object ignore)\r\n   at System.Windows.Application.RunInternal(Window window)\r\n   at System.Windows.Application.Run(Window window)\r\n   at System.Windows.Application.Run()\r\n   at WinHue3.App.Main()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nFirst\nSystem.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Linq.Enumerable\nTSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])","HResult":-2146233079,"Source":"System.Core","WatsonBuckets":"..........

**Comment by Hyrules** [comment]
Yeah got this it's related to group zero. Will fix this thanks.
